version: '2'
services:

  cert:
    build:
      context: .
      dockerfile: Dockerfile-cert
    networks:
      envoymesh:
        aliases:
          - cert
    expose:
      - "8002"
      
  service1:
    build:
      context: .
      dockerfile: Dockerfile-service
    volumes:
      - ./service-envoy.json:/etc/service-envoy.json
    networks:
      envoymesh:
        aliases:
          - service1
    environment:
      - SERVICE_NAME=1
    expose:
      - "443"


networks:
  envoymesh: {}
